# Funding Configuration
# This file enables the "Sponsor" button on GitHub repository pages
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [JSONbored] # GitHub Sponsors profile

